### ISSUE TITLE
Any tutorials on how to run on customized data?

### ISSUE THREAD

**Issue by cwchenwang** [facebookresearch/foundpose#3]
Thanks the authors for the great work. I noticed that current evaluation rely hevily on the BOP dataset format, which many of users from other community(including me) are not familar with. For example, I have customized 3D models and 2D images, is there any simplified script to handle that?

**Comment by thodan** [comment]
Hi @cwchenwang, we currently support only the BOP format which is documented here: https://github.com/thodan/bop_toolkit/blob/master/docs/bop_datasets_format.md

You could either convert your data to the BOP format or implement a loader of your own data format (since FoundPose is a method for single-image pose estimation, there is not much data items to load and all are documented in the link above).
