### ISSUE TITLE
Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same       

### ISSUE THREAD

**Issue by nesi73** [facebookresearch/foundpose#5]
Hello,
I am encountering an error when running the following command:
`python scripts/gen_repre.py --opts-path configs/gen_repre/lmo.json`

The error message is:
```
  File "/home/anaconda3/envs/foundpose_gpu/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

For now, I have temporarily solved the issue by using the CPU instead of CUDA in the line of scripts/gen_repre.py:
`generate_repre(opts, opts.object_dataset, object_lid, device, extractor)`

Does anyone know what the underlying issue might be and how to resolve it correctly using CUDA?

Thank you in advance.

**Comment by jerukan** [comment]
Hello,
I ran into the same issue. Not sure if you have already solved it, but it's because the extractor wasn't loaded onto the GPU in the `gen_repre.py` script. On line 250, I just moved `extractor.to(device)` outside the if statement.

```python
# Prepare a feature extractor.
if extractor is None:
    extractor = feature_util.make_feature_extractor(opts.extractor_name)
extractor.to(device)
```

**Comment by evinpinar** [comment]
Thanks for pointing this! It's now fixed with [this commit](https://github.com/facebookresearch/foundpose/commit/7b39e5bb0199d79372c786fde1cb9bc8946962cd#diff-a10d9afe468fee17eb0c96ca7fdb139343a5d1f507d1fc270c7b837f2e446e63L250).

**Comment by Goddard-Wen** [comment]
![Image](https://github.com/user-attachments/assets/ec5ab79c-2fb6-41f2-a0e5-f5c431fb19e7)

When I use the command:` python scripts/infer.py --opts-path configs/infer/lmo.json`
Encountered an error as shown in the figure while running inferr.py: `RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`

I used the template and representation you provided. Is it because you used CPU for representation that caused my problem: `RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`

To solve this problem, I need to regenerate the template and represent it, because I found that the image of the template, The depth and mask paths are written and there are countless of them.

After regenerating the template and representing it, there should be no problem running inferr.py, right?

Thank you in advance.
